---
- hosts: laradock
  sudo: yes


  tasks: 
   
   - apt: update_cache=yes
   - apt: upgrade=dist

   - name: git, ssh, curl, Docker.io install
     apt: name={{ item }} state=present
     with_items: 
       - git
       - ssh
       - curl
       - docker.io
       - python-pip 
       - python-dev
       - build-essential

   - name: install docker-compose
     shell: pip install -U docker-compose
     
   - name: execute permissions
     shell: chmod +x /usr/local/bin/docker-compose
   
   - name: add key
     shell: sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
     
   - shell: echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" | sudo tee /etc/apt/sources.list.d/docker.list
   - shell: apt-get update

   - name: docker-engine install
     apt: name={{ item }} state=present
     with_items: 
       - docker
       - docker-engine

   - name: docker service restart
     shell: sudo service docker restart 
   
   - name: downlod docker-compose
     shell: curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
   
    
