---
 
 - name: remove laradock 
   shell: sudo rm -rf /home/ubuntu/laradock
   
 - name: laradock Git Clone
   git: repo=https://github.com/LaraDock/laradock.git  dest=/home/ubuntu/laradock version=master
   
 - name: Remove Dockerfile
   shell: rm -rf /home/ubuntu/laradock/nginx/Dockerfile
   
 - name: Remove docker-compose
   shell: rm -rf /home/ubuntu/laradock/docker-compose.yml
   
 - name: Remove index.html
   shell: rm -rf /home/ubuntu/laradock/nginx/www/index.html
   
 - name: Copy Dockerfile File . . . 
   copy: src=Dockerfile dest=/home/ubuntu/laradock/nginx/Dockerfile

 - name: Copy Dockerfile File . . . 
   copy: src=docker-compose.yml dest=/home/ubuntu/laradock/docker-compose.yml owner=root

 - name: Copy Index page File . . . 
   copy: src=index.html dest=/home/ubuntu/laradock/nginx/www/ owner=root

 - name: docker-compose container stop
   shell: cd /home/ubuntu/laradock/ && docker-compose stop
   
 #- name:  all docker container remove 
 # shell: cd /home/ubuntu/laradock/ && docker rm $(docker ps -a -q)
 
 - name: docker-compose container up
   shell: cd /home/ubuntu/laradock/ && docker-compose up -d nginx
   
 - name:  laradock_nginx run 
   shell: kubectl run laradock --image=laradock_nginx --port=80 --hostport=81 && kubectl get pods
